version: '2'
services:
  proxy:
    build: ./proxy
    image: mfay/haproxy:1.1 
    ports:
      - "80:80"
      - "70:70"
    links:
      - weba 
      - webb 
      - webc 
    restart: always
  weba:
    build: ./web 
    restart: always
    env_file: ./web/.env
    links:
      - redis
    depends_on:
      - redis
  webb:
    build: ./web 
    restart: always
    env_file: ./web/.env
    links:
      - redis
    depends_on:
      - redis
  webc:
    build: ./web 
    restart: always
    env_file: ./web/.env
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
