version: '2'
services:
  proxy:
    image: dockercloud/haproxy:1.2.1
    ports:
      - "80:80"
    links:
      - web 
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    build: ./web 
    restart: always
    env_file: ./web/.env
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: redis:3.2
    #ports:
    #  - "6379:6379"
